Repository petretiandrea/home-assistant-tapo-p100, pull requests merged in 2023-09, with the labels that each got.

#495 feat: make proper support for the s500
  README.md
  custom_components/tapo/const.py
Labels: enhancement

#501 feat: device mac tracking
  .devcontainer/devcontainer.json
  custom_components/migrations.py
  custom_components/tapo/__init__.py
  custom_components/tapo/config_flow.py
  custom_components/tapo/const.py
  custom_components/tapo/helpers.py
  custom_components/tapo/hub/tapo_hub.py
  custom_components/tapo/setup_helpers.py
  custom_components/tapo/tapo_device.py
  custom_components/tapo/translations/ar.json
  custom_components/tapo/translations/en.json
  custom_components/tapo/translations/fr.json
  custom_components/tapo/translations/it.json
  custom_components/tapo/translations/pt-BR.json
  requirements_test.txt
  tests/test_find_localdevice.py
Labels: enhancement

#502 feat: UI flow ip change
  README.md
  custom_components/tapo/config_flow.py
Labels: enhancement

#515 fix: migration config entry
  custom_components/tapo/__init__.py
  custom_components/tapo/config_flow.py
  custom_components/tapo/migrations.py
Labels: bug

#524 chore: marked track mac as experimental
  custom_components/tapo/config_flow.py
  custom_components/tapo/translations/ar.json
  custom_components/tapo/translations/de.json
  custom_components/tapo/translations/en.json
  custom_components/tapo/translations/fr.json
  custom_components/tapo/translations/it.json
  custom_components/tapo/translations/pt-BR.json
Labels: documentation, refactoring

#526 feat: experimental ts15
  custom_components/tapo/const.py
Labels: enhancement

#527 add t100 motion sensor
  custom_components/tapo/hub/binary_sensor.py
  custom_components/tapo/hub/sensor.py
  custom_components/tapo/hub/tapo_hub_child_coordinator.py
Labels: enhancement

#528 fix missing binary sensor entity
  custom_components/tapo/binary_sensor.py
  custom_components/tapo/sensors/__init__.py
  custom_components/tapo/siren.py
Labels: bug

#535 fix: smart door and motion sensor
  custom_components/tapo/binary_sensor.py
  custom_components/tapo/hub/binary_sensor.py
  custom_components/tapo/hub/tapo_hub.py
Labels: bug
